name: Trigger Semantic Release

on:
  workflow_call:
    inputs:
      branches:
        required: true
        type: string
      repo_path:
        required: false
        type: string
    secrets:
      token:
        required: true
jobs:
  # Early exit job to complete workflow if branches is not "main"
  No-release:
    if: ${{ inputs.branches != 'main' }}
    runs-on: ubuntu-latest
    steps:
      - name: No release
        run: echo "Branch is not main, no need to release."

  # Execute semantic release only if branches is "main"
  execute-semantic-release:
    if: ${{ inputs.branches == 'main' }}
    uses: Ridvan-bot/workflows/.github/workflows/semantic-release.yml@main
    with:
      branches: "${{ github.ref_name }}"
      repo_path: "${{ inputs.repo_path }}"
    secrets:
      token: ${{ secrets.GH_TOKEN }}  # Pass the GH_TOKEN as 'token' to release.yml
